version: "3"
services:
    jupyter:
        image: jupyter/scipy-notebook
        ports:
            - 8888:8888
    minio:
        image: minio/minio
        ports:
            - 9000:9000
        volumes:
            - mn_vol:/data
        environment:
            - MINIO_ROOT_USER=alashmony
            - MINIO_ROOT_PASSWORD=P@ssM0rd
        command: server /data
volumes:
    mn_vol:
